name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  sample-workflow:
    runs-on: ubuntu-latest

    steps:

      - name: Random Worflow Success
        run: |
          echo "test"
          sleep 100
          echo "looks good"
          random=$(shuf -i 0-1 -n 1)
          if [ $random -eq 0 ]; then
            exit 1
          fi
          

      - name: Force failure if requested
        if: contains(github.event.pull_request.title, '(fail)')
        run: |
          echo "Failing because PR title contains (fail)"
          exit 1

      
