name: Failing Workflow 

on:
  pull_request: 
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  failing-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Fail
        run: |
          echo "This workflow will fail"
          sleep 30
          exit 1
    
