name: Merge Group Workflow

on:
  merge_group: 

permissions:
  contents: read

jobs:
  random-workflow-success:
    runs-on: ubuntu-latest

    steps:

      - name: Random Success
        run: |
          sleep 100
          random=$(shuf -i 0-1 -n 1)
          if [ $random -eq 0 ]; then
            exit 1
          fi
          

      
